# Generated by Django 6.1.1 on 2026-09-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('biografia', models.TextField()),
            ],
        ),
    ]
