# Generated by Django 6.1.1 on 2026-09-22 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('core', '0003_alter_livro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.genero'),
            preserve_default=False,
        ),
    ]
