# Generated by Django 6.1.1 on 2026-09-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('core', '0004_livro_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.ManyToManyField(to='biblioteca.genero'),
        ),
    ]
